image: node:latest
  
cache:
  paths:
  - node_modules/
  
stages:
  - build
  - apidocs
  - test
  - deploy

build_dev:
  stage: build
  artifacts:
    paths:
    - ./
    expire_in: 2h
  script:
    - npm install
    - npm run build
  except: 
    - master
  
build_prod:
  stage: build
  artifacts:
    paths:
    - ./
    expire_in: 2h
  script:
    - npm install
    - npm run deploy
  only: 
    - master
    - staging

test_build_api_docs:
  stage: apidocs
  script:
    - npm install
    - npm run apidocs

test:
  stage: test
  variables: 
    NODE_ENV: "test"
    DATABASE_HOST: "mongo"
    DATABASE_PORT: "27017"
    DATABASE: "iot-fablab"
    DATABASE_DUMP: "dump/iot-fablab"
  services:
    - mongo
  script:
   - 'which mongorestore || (apt-get update -y && apt-get install mongodb -y)'
   - apt-get install wget -y
   - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
   - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
   - apt-get update && apt-get -y install google-chrome-stable
   - cd db-seeds
   - bash scripts/import.sh $DATABASE_HOST $DATABASE_PORT $DATABASE $DATABASE_DUMP
   - cd ..
   - NODE_ENV=$NODE_ENV
   - npm install
   - npm run test
    
deploy:
  stage: deploy
  environment:
    name: staging
    url: $SERVER_ADDRESS
  when: manual
  only:
   - staging
  before_script:
   - 'which base64 || ( apt-get update -y && apt-get install base64 -y )'
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - 'which rsync || (apt-get update -y && apt-get install rsync -y)'
   - mkdir -p ~/.ssh
   - eval $(ssh-agent -s)
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   - ssh-add <(echo "$STAGING_PRIVATE_KEY" | base64 --decode)
  script:
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "rm -rf /home/$RUNNER_USERNAME/apps/$PROJECT_NAME && mkdir /home/$RUNNER_USERNAME/apps/$PROJECT_NAME"
   - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='node_modules' --delete-excluded ./ $RUNNER_USERNAME@$SERVER_ADDRESS:/home/$RUNNER_USERNAME/apps/$PROJECT_NAME
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "cd /home/$RUNNER_USERNAME/apps/$PROJECT_NAME && npm install && npm run build && rm -rf /var/www/html/* && cp .htaccess dist/.htaccess && cp -r dist/* /var/www/html"
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "cd /home/$RUNNER_USERNAME/apps/$PROJECT_NAME && pm2 stop $PROJECT_NAME && pm2 start npm --name \"$PROJECT_NAME\" -- run api-serve"
