image: node:10
  
cache:
  paths:
  - node_modules/
  
stages:
  - build
  - apidocs
  - test
  - deploy

before_script:
  - npm install
  - npm run build

build_dev:
  stage: build
   #artifacts:
   #  paths:
   #  - ./
   #  expire_in: 2h
  script: 
    - echo "done"
  except: 
    - master
    - develop
    - fix/ci
  
build_prod:
  stage: build
  before_script:
    - npm install
   #artifacts:
    # paths:
    # - ./
    # expire_in: 1 day
  script:
    - npm run deploy-prod
  only: 
    - master
    - develop
    - fix/ci

build_staging:
  stage: build
  before_script:
    - npm install
   #artifacts:
    # paths:
    # - ./
    # expire_in: 1 day
  script:
    - npm run deploy-staging
  only: 
    - master
    - develop
    - fix/ci

test_build_api_docs:
  stage: apidocs
  script:
    - npm run apidocs

test:
  stage: test
  variables: 
    NODE_ENV: "test"
    DATABASE_HOST: "mongo"
    DATABASE_PORT: "27017"
    DATABASE: "iot-fablab"
    DATABASE_DUMP: "dump/iot-fablab"
  services:
    - mongo
  script:
   - 'which mongorestore || (apt-get update -y && apt-get install mongodb -y)'
   - apt-get install wget -y
   - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
   - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
   - apt-get update && apt-get -y install google-chrome-stable
   - cd db-seeds
   - bash scripts/import.sh $DATABASE_HOST $DATABASE_PORT $DATABASE $DATABASE_DUMP
   - cd ..
   - NODE_ENV=$NODE_ENV
   - npm run test
    
deploy_staging:
  stage: deploy
  environment:
    name: staging
  variables: 
    NODE_ENV: "prod"
    DATABASE_HOST: "localhost"
    DATABASE_PORT: "27017"
    DATABASE: "iot-fablab-staging"
    DATABASE_DUMP: "dump/iot-fablab"
  when: manual
  only:
   - master
   - develop
   - fix/ci
  before_script:
   - 'which base64 || ( apt-get update -y && apt-get install base64 -y )'
   - 'which mongorestore || (apt-get update -y && apt-get install mongodb -y)'
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - 'which rsync || (apt-get update -y && apt-get install rsync -y)'
   - mkdir -p ~/.ssh
   - eval $(ssh-agent -s)
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   - ssh-add <(echo "$STAGING_PRIVATE_KEY" | base64 --decode)
   - npm install && npm run deploy-staging
  script:
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "rm -rf /home/$RUNNER_USERNAME/apps/$PROJECT_NAME && mkdir /home/$RUNNER_USERNAME/apps/$PROJECT_NAME"
   - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='node_modules' --delete-excluded ./ $RUNNER_USERNAME@$SERVER_ADDRESS:/home/$RUNNER_USERNAME/apps/$PROJECT_NAME
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "cd /home/$RUNNER_USERNAME/apps/$PROJECT_NAME && npm install && rm -rf /var/www/html/* && cp -r dist/. /var/www/html"
   # Delete this line if the database shall not be dropped
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "mongo iot-fablab-staging --eval \"db.dropDatabase()\" && cd /home/$RUNNER_USERNAME/apps/$PROJECT_NAME/db-seeds && bash scripts/import.sh $DATABASE_HOST $DATABASE_PORT $DATABASE $DATABASE_DUMP"
   # Comment end
   # Delete old process if running, otherwise true and start process
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "cd /home/$RUNNER_USERNAME/apps/$PROJECT_NAME && pm2 delete $PROJECT_NAME || true"
   - ssh -p22 $RUNNER_USERNAME@$SERVER_ADDRESS "cd /home/$RUNNER_USERNAME/apps/$PROJECT_NAME && pm2 start ecosystem-staging.config.js"


deploy_production:
  stage: deploy
  environment:
    name: production
  variables: 
    NODE_ENV: "prod"
    DATABASE_HOST: "localhost"
    DATABASE_PORT: "27017"
    DATABASE: "iot-fablab"
    DATABASE_DUMP: "dump/iot-fablab"
  when: manual
  only:
   - master
   - develop
   - fix/ci
  before_script:
   - 'which base64 || ( apt-get update -y && apt-get install base64 -y )'
   - 'which mongorestore || (apt-get update -y && apt-get install mongodb -y)'
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - 'which rsync || (apt-get update -y && apt-get install rsync -y)'
   - mkdir -p ~/.ssh
   - eval $(ssh-agent -s)
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   - ssh-add <(echo "$PRODUCTION_PRIVATE_KEY" | base64 --decode)
   - npm install && npm run deploy-prod
  script:
   - echo "$PRODUCTION_RUNNER_USERNAME@$PRODUCTION_SERVER_ADDRESS with path /home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME"
   - ssh -p22 $PRODUCTION_RUNNER_USERNAME@$PRODUCTION_SERVER_ADDRESS "rm -rf /home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME && mkdir /home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME"
   - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='node_modules' --delete-excluded ./ $PRODUCTION_RUNNER_USERNAME@$PRODUCTION_SERVER_ADDRESS:/home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME
   - ssh -p22 $PRODUCTION_RUNNER_USERNAME@$PRODUCTION_SERVER_ADDRESS "cd /home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME && npm install && rm -rf /var/www/html/* && cp -r dist/. /var/www/html"
   # Delete this line if the database shall not be dropped
   # WARNING! - ssh -p22 $PRODUCTION_RUNNER_USERNAME@$PRODUCTION_SERVER_ADDRESS "mongo iot-fablab --eval \"db.dropDatabase()\" && cd /home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME/db-seeds && bash scripts/import.sh $DATABASE_HOST $DATABASE_PORT $DATABASE $DATABASE_DUMP"
   # Comment end
   # Delete old process if running, otherwise true and start process
   - ssh -p22 $PRODUCTION_RUNNER_USERNAME@$PRODUCTION_SERVER_ADDRESS "cd /home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME && pm2 delete $PROJECT_NAME || true"
   - ssh -p22 $PRODUCTION_RUNNER_USERNAME@$PRODUCTION_SERVER_ADDRESS "cd /home/$PRODUCTION_RUNNER_USERNAME/apps/$PROJECT_NAME && pm2 start ecosystem-prod.config.js"
