addons:
  ssh_known_hosts: sandbox.ipoesse.de

language: node_js
node_js:
- 12
os: linux
dist: bionic

branches:
  only:
  - develop
cache: 
  directories:
    - node_modules

install:
- npm install
script: npm run deploy-staging
before_deploy:
- openssl aes-256-cbc -K $encrypted_84f7f15250c2_key -iv $encrypted_84f7f15250c2_iv
  -in deploy-rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: s3
  access_key_id: $aws_key
  secret_access_key: $aws_secret_access_key
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    branch: develop
  bucket: travisdeploy
  region: eu-central-1
- provider: codedeploy
  access_key_id: $aws_key
  secret_access_key: $aws_secret_access_key
  bucket: travisdeploy
  key: latest.zip
  bundle_type: zip
  application: print4life
  deployment_group: print4life
  region: eu-central-1
  on: *2

notifications:
  email:
    recipients:
    - ian-github@ipoesse.de
    on_success: always
    on_failure: always